### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by jkiss** [Lynnhan95/nodePractice#1]
I'm a font-end developer too, if you need a node framework, you can try mine [Node-Express-Template](https://github.com/jkiss/Node-Express-Template)

**Comment by Lynnhan95** [comment]
Hey Mr.B

Thanks! I'll check that out!谢谢。



Best,
Lynne
________________________________
发件人: Mr.B <notifications@github.com>
发送时间: 2019年9月5日 16:00
收件人: Lynnhan95/nodePractice <nodePractice@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [Lynnhan95/nodePractice] Hi (#1)


I'm a font-end developer too, if you need a node framework, youcan try mine Node-Express-Template<https://github.com/jkiss/Node-Express-Template>

―

**Comment by jkiss** [comment]
对你的简历很感兴趣，你有什么社交账号可以加一下吗？回国的话方便联系 :)

**Comment by Lynnhan95** [comment]
你好：）希望多交流，
我的linkedin是：https://www.linkedin.com/in/guojun-lynne-han-082066173/
我的微信ID是：Lynnhan95
我的邮箱是：han536@purdue.edu

________________________________
发件人: Mr.B <notifications@github.com>
发送时间: 2019年9月6日 12:03
收件人: Lynnhan95/nodePractice <nodePractice@noreply.github.com>
抄送: Guojun Han <han536@purdue.edu>; Comment <comment@noreply.github.com>
主题: Re: [Lynnhan95/nodePractice] Hi (#1)


对你的简历很感兴趣，你有什么社交账号可以加一下吗？回国的话方便联系 :)

―

**Comment by jkiss** [comment]
got it，技术问题可以随时交流哈
